### ISSUE TITLE
Add Discussions

### ISSUE THREAD

**Issue by ScottMonaghan** [vade/No-Adult-Left-Behind#1]
I think at the stage we're at, rather than working out of the wiki, it would make more sense to take advantage of Github's newish forum-like feature Discussions:
https://docs.github.com/en/discussions

I don't know the deets, but I'm pretty sure @vade can enable this as owner of the repo.

**Comment by ScottMonaghan** [comment]
Here is the documentation on how to enable Discussions in a repo: 
https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository

**Comment by vade** [comment]
https://github.com/vade/No-Adult-Left-Behind/discussions/2
